In [1]:
import os
import sys
import pandas as pd
from lib.display import Display
from lib.database import Database
from lib.schema import Schema

db = Database(Schema.FEMFIT)   
Display.header('FeMFit study on ALP', 'h1')

Display.header('Participants', 'h3')
participants_df = db.get_participants()
Display.frame(participants_df, 5)
Display.header('Responses', 'h3')
responses_df = db.get_responses()
Display.frame(responses_df, 5)
Display.header('Wearables', 'h3')
wearables_df = db.get_wearables()
Display.frame(wearables_df, 5)

In [2]:
from lib.studies.femfit_study import FemfitStudy 
from lib.participant_builder import ParticipantsBuilder

study = FemfitStudy()
print('Study:', study.name())
print('Last donation:', responses_df['AUTHORED'].max().strftime("%Y-%m-%d"))

builder = ParticipantsBuilder(study, participants_df, responses_df)
df = builder \
    .add_last_donation() \
    .add_all_submissions() \
    .get() \
    .sort_values(by=['LAST_DONATION'], ascending=False)

Display.frame(df, 5)

Study: FeMFit
Last donation: 2022-03-27